name: push
on:
  workflow_dispatch:
  push:
    branches:
       - master
       - main
    tags:
       - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      SHA8: ${GITHUB_SHA::8}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # - name: "Push source and download translate files from transifex"
      #   uses: docker://sergioisidoro/github-transifex-action:v0.2.0
      #   with:
      #       TX_TOKEN: ${{ secrets.TX_TOKEN }}
      #       git_flow: false
      #       github_token: ${{ secrets.GITHUB_TOKEN }}
      #       pull_translations: true
      #       pull_sources: false
      #       push_translations: false
      #       push_sources: true
      - run: |
              sudo chown $(whoami) -R  spoonbill/locales/
              pybabel compile -f -D spoonbill -d spoonbill/locales/
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ghcr.io/${{ github.repository_owner }}/spoonbill:latest
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - run: |
              pip install --upgrade setuptools wheel
              python setup.py sdist bdist_wheel